### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by DarrenSmallwood** [CyberPunkMetalHead/Bitcoin-Surge-Trading-Alpha#2]
Demo account is authenticated using MT5 and XBTFX but the following error is received: 

Traceback (most recent call last):
  File "C:\repos\Bitcoin-Surge-Trading-Alpha\bitcoin-surge-trading-bot-alpha.py", line 159, in <module>
    trade()
  File "C:\repos\Bitcoin-Surge-Trading-Alpha\bitcoin-surge-trading-bot-alpha.py", line 66, in trade
    current_buy_price, current_sell_price = get_current_prices()
  File "C:\repos\Bitcoin-Surge-Trading-Alpha\bitcoin-surge-trading-bot-alpha.py", line 57, in get_current_prices
    current_buy_price = mt5.symbol_info_tick(CRYPTO)[2]
TypeError: 'NoneType' object is not subscriptable

**Comment by DarrenSmallwood** [comment]
Line 57: current_buy_price = mt5.symbol_info_tick(CRYPTO)[2]

Exception has occurred: TypeError
'NoneType' object is not subscriptable

**Comment by CyberPunkMetalHead** [comment]
Looks like on some versions of MT5 the symbol for crypto should have an "!" appended, so instead of CRYPTO = "BTCUSD" try CRYPTO = "BTCUSD!". This is likely due to the fact that your pairing is on USDT and not fiat USD.

**Comment by DarrenSmallwood** [comment]
That worked, thank you
